name: memory_game
description: Memory Game League of Legends

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.0.0

  cupertino_icons: 1.0.6

environment:
  sdk: '>=2.12.0 <3.0.0'

flutter:
  assets:
    - assets/INICIO.JPG
    - assets/SELECCIONDEMODOS.jpg
    - assets/MODOSDEJUEGOS.jpg
    - assets/CHAMPS/campeon1.png
    - assets/CHAMPS/campeon2.png
    - assets/CHAMPS/campeon3.png
    - assets/CHAMPS/campeon4.png
    - assets/CHAMPS/campeon5.png
    - assets/CHAMPS/campeon6.png
    - assets/CHAMPS/campeon7.png
    - assets/CHAMPS/campeon8.png
    - assets/CHAMPS/campeon9.png
    - assets/CHAMPS/campeon10.png
    - assets/placeholder.jpg
    - assets/VICTORIA.jpg